### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [zach111694/molloyLife#14]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by zach111694** [comment]
Thanks for the heads up. I'll get on it soon

**Comment by zach111694** [comment]
@SantiVargas MIT was recommended so we have the correct license. closing this issue, thanks Santi
